name: "Deployed Promotion Action"
description: "Promotion Action Template to interact with deployed cli"
author: "Deployix"

inputs:
  description:
    description: "Description of the promotion"
    required: true
  
  promotionName:
    description: "Name of the promotion resource to target"
    required: true

  githubToken:
    description: "Github token used to authenticate against your repo"
    required: false

outputs:
  promotedChannel:
    description: "Channel that was promoted"
  
  promotedVersion:
    description: "Version that was promoted"

  timePromoted:
    description: "Time that the promotion was made"

  error:
    description: "The error message if the promotion failed"

runs:
  using: "docker"
  image: "Dockerfile"