name: "Deployed Promotion Action"
description: "Promotion Action Template to interact with deployed sdk"
author: "Deployix"

inputs:
  description:
    description: "Description of the promotion"
    required: true

  promotionName:
    description: "Name of the promotion resource to target"
    required: true

  workingDir:
    description: "Working directory that contains your repo. Defaults to '.'"
    default: "."
    required: false

  githubPAT:
    description: "Personal Access token used to commit changes"
    required: true

outputs:
  promotedChannel:
    description: "Channel that was promoted"

  promotedVersion:
    description: "Version that was promoted"

  timePromoted:
    description: "Time that the promotion was made"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_PAT: ${{ inputs.githubPAT }}
