name: Build
on: [push]
jobs:
  promotedChannel:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/deployix/deployed-github-actions
        credentials:
            username: <YOUR_USERNAME>
            password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    steps:
      - uses: extractions/netrc@v2
        with:
          machine: github.com
          username: deployed-ci
          password: SuperSecretPassword
      - uses: deployix/deployed-github-actions@main
        if: always()
        with:
          secrets: |
            "netrc=~/.netrc"