name: Build
on: [push]
jobs:
  build:
    name: Promote
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: deployix/deployed-github-actions@main
        if: always()
        with:
          build-args: |
            GITHUB_USERNAME=${{ inputs.githubUsername }}
            GITHUB_TOKEN=${{ inputs.githubToken }}
