name: Promote 
on: [push]
jobs:
  promotedChannel:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: deployed-ci
          password: SuperSecret
      - run: "cat ~/.netrc && sleep 10"
      - name: promote local-to-dev
        uses: docker://ghcr.io/deployix/deployed-github-actions
        if: always()
        with:
          promotionName: "local-to-dev"