name: Build
on: [push]
jobs:
  promotedChannel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: deployix/deployed-github-actions@main
        if: always()
        with:
          promotionName: "local-to-dev"
          githubPAT: ${{ secrets.SUPER_SECRET_PAT }}