name: Build
on: [push]
jobs:
  build:
    name: Promote
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/netrc@v1
        with:
          machine: github.com
          username: deployed-ci
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: deployix/deployed-github-actions@main
        if: always()
        with:
          secrets: |
            "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
            "GITHUB_USERNAME=${{ inputs.githubUsername}}"
