name: Build
on: [push]
jobs:
  promotedChannel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/netrc@v2
        with:
          machine: github.com
          username: deployed-ci
          password: SuperSecretPassword
      - uses: deployix/deployed-github-actions@main
        if: always()
        with:
          promotionName: "local-to-dev"