name: Build
on: [push]
jobs:
  build:
    name: Promote
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - uses: deployix/deployed-github-actions@main
        if: always()
        with:
          githubToken: ${{ secrets.REPO_GITHUB_SECRET }}
          githubUsername: "deployed-ci"
          description: "test description"
          promotionName: "local-to-dev"
